# Forecasting Time-series
###### Juan Camilo Mercado

## Carga de Librerías

In [ ]:
# Manipulación de datos
import polars as pl
import pandas as pd
import numpy as np

# Modelado
from xgboost import XGBRegressor

#Visualización
import plotly.graph_objects as go

# Validación y parametrización
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import TimeSeriesSplit

# Guardar y cargar modelos
import joblib

### Carga de datos

In [ ]:
df = pl.read_csv('./Data/retail_store_inventory.csv')

shape: (5, 15)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Date      ┆ Store ID ┆ Product   ┆ Category  ┆ … ┆ Weather   ┆ Holiday/P ┆ Competito ┆ Seasonali │
│ ---       ┆ ---      ┆ ID        ┆ ---       ┆   ┆ Condition ┆ romotion  ┆ r Pricing ┆ ty        │
│ str       ┆ str      ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ str       ┆           ┆   ┆ str       ┆ i64       ┆ f64       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2022-01-0 ┆ S001     ┆ P0001     ┆ Groceries ┆ … ┆ Rainy     ┆ 0         ┆ 29.69     ┆ Autumn    │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2022-01-0 ┆ S001     ┆ P0002     ┆ Toys      ┆ … ┆ Sunny     ┆ 0         ┆ 66.16     ┆ Autumn    │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2022-01-0 ┆ S001     ┆ P0003     ┆ Toys      ┆ … ┆ Sunny     ┆ 1         ┆ 31.32     ┆ Summer    │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2022-01-0 ┆ S001     ┆ P0004     ┆ Toys      ┆ … ┆ Cloudy    ┆ 1         ┆ 34.74     ┆ Autumn    │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2022-01-0 ┆ S001     ┆ P0005     ┆ Electroni ┆ … ┆ Sunny     ┆ 0         ┆ 68.95     ┆ Summer    │
│ 1         ┆          ┆           ┆ cs        ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Entendimiento de datos

In [195]:
df.shape

(73100, 15)

In [196]:
df.describe()

shape: (9, 16)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ Date      ┆ Store ID ┆ Product   ┆ … ┆ Weather   ┆ Holiday/P ┆ Competito ┆ Seasonali │
│ ---       ┆ ---       ┆ ---      ┆ ID        ┆   ┆ Condition ┆ romotion  ┆ r Pricing ┆ ty        │
│ str       ┆ str       ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆ str       ┆   ┆ str       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 73100     ┆ 73100    ┆ 73100     ┆ … ┆ 73100     ┆ 73100.0   ┆ 73100.0   ┆ 73100     │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0         │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 0.497305  ┆ 55.146077 ┆ null      │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 0.499996  ┆ 26.191408 ┆ null      │
│ min       ┆ 2022-01-0 ┆ S001     ┆ P0001     ┆ … ┆ Cloudy    ┆ 0.0       ┆ 5.03      ┆ Autumn    │
│           ┆ 1         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ 32.68     ┆ null      │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ 55.01     ┆ null      │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 1.0       ┆ 77.82     ┆ null      │
│ max       ┆ 2024-01-0 ┆ S005     ┆ P0020     ┆ … ┆ Sunny     ┆ 1.0       ┆ 104.94    ┆ Winter    │
│           ┆ 1         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Se observa que en calidad de datos no hay valores faltantes ni de tipos incorrecos, por lo que se infiere cumple con las reglas del negocio además de que todas las columnas tienen el tipo de dato correcto. No hay duplicidad en os datos.

### Feature Engineering

En esta sección se crean variables derivadas del tiempo y se transforman variables categóricas. El día de la semana y el mes permiten capturar estacionalidad en la demanda, como patrones de consumo semanales o mensuales. Estas variables permiten al modelo incorporar contexto de negocio además de información temporal.

Se calculan variables que aportan valor como las ganancias titales en la fecha, ganancias netas (sin descuento) y la referencia con el precio de la competencia.

In [197]:
df = df.with_columns([
    pl.col("Date").str.strptime(pl.Date, '%Y-%m-%d').dt.weekday().alias("weekday"),
    pl.col("Date").str.strptime(pl.Date, '%Y-%m-%d').dt.month().alias("month"),
])

In [198]:
df = df.with_columns([(df["Units Sold"] * df["Price"]).alias("Revenue")])

In [199]:
df = df.with_columns([(df["Revenue"] - df["Discount"]).alias("Net Revenue"), 
                      
                     (df["Price"] - df["Competitor Pricing"]).alias("Competitor Price Difference")])

Igualmente, se construyen las variables lags, que representan valores pasados de la variable objetivo, lo que permite capturar dependencia temporal. El lag de un día refleja inercia inmediata en la demanda, mientras que el lag de siete días captura patrones semanales. La media móvil de siete días suaviza la serie y ayuda a identificar tendencias generales. Todas estas transformaciones se realizan por combinación de tienda y producto para preservar la independencia de cada serie temporal.

In [200]:
df = df.with_columns([
    pl.col("Units Sold")
      .shift(1)
      .over(["Store ID", "Product ID"])
      .alias("lag_1"),

    pl.col("Units Sold")
      .shift(7)
      .over(["Store ID", "Product ID"])
      .alias("lag_7"),
])

df = df.with_columns([
    pl.col("Units Sold")
      .rolling_mean(window_size=7)
      .over(["Store ID", "Product ID"])
      .alias("rolling_mean_7")
])

df.tail()

shape: (5, 23)
┌────────────┬──────────┬────────────┬───────────┬───┬──────────────┬───────┬───────┬──────────────┐
│ Date       ┆ Store ID ┆ Product ID ┆ Category  ┆ … ┆ Competitor   ┆ lag_1 ┆ lag_7 ┆ rolling_mean │
│ ---        ┆ ---      ┆ ---        ┆ ---       ┆   ┆ Price        ┆ ---   ┆ ---   ┆ _7           │
│ str        ┆ str      ┆ str        ┆ str       ┆   ┆ Difference   ┆ i64   ┆ i64   ┆ ---          │
│            ┆          ┆            ┆           ┆   ┆ ---          ┆       ┆       ┆ f64          │
│            ┆          ┆            ┆           ┆   ┆ f64          ┆       ┆       ┆              │
╞════════════╪══════════╪════════════╪═══════════╪═══╪══════════════╪═══════╪═══════╪══════════════╡
│ 2024-01-01 ┆ S005     ┆ P0016      ┆ Furniture ┆ … ┆ 1.28         ┆ 54    ┆ 43    ┆ 82.571429    │
│ 2024-01-01 ┆ S005     ┆ P0017      ┆ Toys      ┆ … ┆ -1.21        ┆ 162   ┆ 119   ┆ 125.285714   │
│ 2024-01-01 ┆ S005     ┆ P0018      ┆ Clothing  ┆ … ┆ 0.2          ┆ 111   ┆ 5     ┆ 99.857143    │
│ 2024-01-01 ┆ S005     ┆ P0019      ┆ Toys      ┆ … ┆ -2.66        ┆ 17    ┆ 213   ┆ 144.428571   │
│ 2024-01-01 ┆ S005     ┆ P0020      ┆ Groceries ┆ … ┆ -1.13        ┆ 40    ┆ 31    ┆ 115.714286   │
└────────────┴──────────┴────────────┴───────────┴───┴──────────────┴───────┴───────┴──────────────┘

### Preparación de datos

In [201]:
df = df.sort(["Store ID", "Product ID", "Date"])

In [202]:
pdf = df.to_pandas()

In [203]:
target = "Units Sold"

A todas las variables categóricas se codifican para poder usarlas en las predicciones.

In [204]:
pdf = pd.get_dummies(pdf, columns=[
    "Store ID",
    "Product ID",
    "Weather Condition",
    "Holiday/Promotion",
    "Seasonality",
    "Category",
    "Region"
])

### Entrenamiento de modelos

In [205]:
split = int(len(pdf) * 0.8)

train = pdf[:split]
test = pdf[split:]

In [206]:
X_train = train.drop(columns=[target, "Date"])
y_train = train[target]

X_test = test.drop(columns=[target, "Date"])
y_test = test[target]

Se establecen las condiciones para hacer GridSearch de hiperparámetros más adelante.

In [207]:
tscv = TimeSeriesSplit(n_splits=3)

param_grid = {

    "n_estimators": [100, 300],

    "learning_rate": [0.01, 0.05],

    "max_depth": [4, 6],

    "subsample": [0.8, 1.0],

    "colsample_bytree": [0.8, 1.0]
}

Se elige el modelo XGBoost, que es capaz de capturar relaciones no lineales y complejas entre variables habiendo muchas categorías, al contrario que (S)ARIMA o Prophet. Los hiperparámetros controlan la complejidad del modelo y ayudan a evitar overfitting, permitiendo una buena generalización sobre datos no vistos.

In [208]:
xgb = XGBRegressor(
    random_state=777
)

Se buscan los mejores hiperparámetros con GridSearch que ayuda a probar todas las combinaciones dadas eligiendo la de mejor ajuste.

In [209]:
grid_search = GridSearchCV(

    estimator=xgb,

    param_grid=param_grid,

    scoring="neg_mean_absolute_error",

    cv=tscv,

    verbose=1,

    n_jobs=-1
)

grid_search.fit(X_train, y_train)

model = grid_search.best_estimator_

Fitting 3 folds for each of 32 candidates, totalling 96 fits

Con el mejor modelo, se entrena al mismo.

In [210]:

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

En esta etapa se generan predicciones sobre el conjunto de prueba. Estas predicciones representan la estimación de la demanda futura basada en los patrones aprendidos durante el entrenamiento.

In [211]:
preds = model.predict(X_test)

En esta celda se evalúa el desempeño del modelo utilizando métricas estándar de regresión. El MAE mide el error absoluto promedio, el RMSE penaliza errores grandes y el MAPE expresa el error en términos porcentuales, lo cual es especialmente útil para interpretación en contextos de negocio.

In [212]:
def evaluate(y_true, y_pred):

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    return mae, rmse


evaluate(y_test, preds)

(2.838449001312256, np.float64(3.9572580315845007))

El modelo obtuvo un MAE de 2.83, lo que indica que, en promedio, las predicciones de demanda presentan un error aproximado de 2.88 unidades vendidas respecto a los valores reales. Esta métrica permite interpretar el desempeño del modelo de manera directa en las mismas unidades del negocio, facilitando la comprensión del impacto práctico del error. 

Por otro lado, el RMSE obtenido fue de 3.96, valor ligeramente superior al MAE debido a que esta métrica penaliza con mayor intensidad los errores grandes. 

La diferencia moderada entre ambas métricas sugiere que el modelo mantiene un comportamiento relativamente estable y que no presenta una cantidad significativa de predicciones extremadamente alejadas de los valores reales. 

En conjunto, estos resultados indican que el modelo logra capturar adecuadamente los patrones de demanda presentes en los datos, manteniendo un nivel de error razonable para un problema de forecasting en retail.

In [ ]:
results_df = test[['Date']].copy()
results_df['Real'] = y_test.values
results_df['Predicción'] = preds

results_df['Date'] = pd.to_datetime(results_df['Date'])


fig = go.Figure()

fig.add_trace(go.Scatter(
    x=results_df['Date'],
    y=results_df['Real'],
    mode='lines',
    name='Valores Reales',
    line=dict(color='blue', width=2)
))

fig.add_trace(go.Scatter(
    x=results_df['Date'],
    y=results_df['Predicción'],
    mode='lines',
    name='Predicciones',
    line=dict(color='red', width=2, dash='dash')
))

fig.update_layout(
    title='Predicciones vs Valores Reales (Units Sold)',
    xaxis_title='Fecha',
    yaxis_title='Units Sold',
    hovermode='x unified',
    height=600
)

fig.show()

Teniendo este modelo analizado y funcionando correctamente sin caer en el overfit ni sin ser muy impreciso se decide exportarlo para su uso y sus columnas para la construcción del reporte.

In [213]:
joblib.dump(model, "./Models/xgboost_forecast.pkl")

model_columns = X_train.columns
joblib.dump(model_columns, "models/model_columns.pkl")

['models/model_columns.pkl']